task :default => :run

task :run do
  sh "make"
end

task :redo do
  f = ENV["F"] || Dir["ch??.c"].sort.last
  headers = `cproto #{f} 2> /dev/null`

  file = File.read f
  file[/\/\* ch\d+\.c \*\/.+\/\* DONE \*\//m] = headers + "/* DONE */"

  File.rename f, "#{f}~"
  File.open f, "w" do |io|
    io.write file
  end

  puts "Updated #{f} headers"
end
