hellooo_world: hellooo_world.c
	cc -std=c99 -Wall hellooo_world.c -o hellooo_world
	./hellooo_world
hello_world: hello_world.c
	cc -std=c99 -Wall hello_world.c -o hello_world
	./hello_world
clean:
	rm hello_world hellooo_world
